export const theme = {
  colors: {
    primary: '#0A5C36',
    primaryLight: '#0D7A48',
    primaryDark: '#073D24',
    secondary: '#D4A843',
    goldLight: '#F5E6C8',
    goldDark: '#B8922E',
    surface: '#FFFFFF',
    background: '#F8F9FA',
    backgroundAlt: '#F0F2F5',
    text: '#1A1A2E',
    textSecondary: '#6B7280',
    textInverse: '#FFFFFF',
    textGold: '#8B6914',
    error: '#DC2626',
    errorLight: '#FEE2E2',
    success: '#059669',
    successLight: '#D1FAE5',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    overlay: 'rgba(0,0,0,0.5)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    xxxl: 32,
    huge: 40,
    massive: 48,
  },
  fontSize: {
    xs: 11,
    sm: 13,
    md: 15,
    lg: 17,
    xl: 20,
    xxl: 24,
    xxxl: 30,
    huge: 36,
  },
  borderRadius: {
    sm: 6,
    md: 10,
    lg: 14,
    xl: 20,
    full: 9999,
  },
  shadow: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 5,
    },
  },
} as const;

export type Theme = typeof theme;